<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello!</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//cdn.livechatinc.com/boilerplate/1.1.css">
    <link rel="stylesheet" href="css/style.css">
    
    
    <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
    
  </head>  
  <body>
    <h1>Hi there! </h1>
    
    <p>
      Let's see agent's details
    </p>
    <br />
    <div id="profile-data">
      <ul class="result">
      </ul>
    </div>
    
    
    <script src="js/script.js"></script>
  </body>
</html>
